#!/usr/bin/env zsh

cd $HOME/.vim/bundle
bfile="bundles.txt"

get() {
    for i in `cat $bfile`; do
        git clone https://github.com/$i.git 2>/dev/null
    done
    return 0
}

update() {
    for i in *(/); do
        pushd $i
        print $i
        git pull
        popd
    done
}

case $1 in
    "g" | "get"    ) get     ;;
     *             ) update  ;;
esac
