#!/bin/zsh

[[ ! -d ~/tmp ]] && mkdir ~/tmp
[[ ! -d ~/.vimundo ]] && mkdir ~/.vimundo

# backup old vimrc
[[ -e ~/.vimrc ]] && mv ~/.vimrc ~/.vimrc_backup_$(date +%s)

print "(s)mall or (b)ig vimrc?"
read -q ANSWER
print # newline

case "$ANSWER" in 
    "s")
        ln -s ~/.vim/vimrc_mini ~/.vimrc
        ;;
    "b")
        ln -s ~/.vim/vimrc ~/.vimrc
        ~/.vim/bundle/b g
        ;;
esac
