#!/bin/sh

[ ! -d ~/tmp ] && mkdir ~/tmp
[ ! -d ~/.vimundo ] && mkdir ~/.vimundo

# backup old vimrc
[ -e ~/.vimrc ] && mv ~/.vimrc ~/.vimrc_backup_$(date +%s)

echo "(s)mall or (b)ig vimrc?"
echo "big version requires at least zsh and git"
read ANSWER

case "$ANSWER" in 
    "s")
        ln -s ~/.vim/vimrc_mini ~/.vimrc
        ;;
    "b")
        ln -s ~/.vim/vimrc ~/.vimrc
        ~/.vim/bundle/b g
        ;;
esac
